name: Validation Jobs

on:
  workflow_call:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment/action.yaml

  typescheck:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: ./.github/actions/setup-environment/action.yaml

      - name: Types check
        run: pnpm typecheck

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: ./.github/actions/setup-environment/action.yaml

      - name: Lint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: ./.github/actions/setup-environment/action.yaml

      - name: Run tests
        run: pnpm test
